### ISSUE TITLE
Fix menu button on mobile

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#18]
On mobile browsers such as Safari for IOS, the hamburger icon does not work. This may be an error on multiple devices.

The proper function of the hamburger is that it open a menu with all of the browsable pages.

**Comment by aryatalathi** [comment]
i would like to contribute and solve this issue

**Comment by William-McGonagle** [comment]
@aryatalathi - I think this is an old problem that's already been fixed. But still, if you want to work on an issue, I would recommend #19. Cheers!
