### ISSUE TITLE
Add projects to the open-source page

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#19]
The open-source projects page was just created and it links to our licenses, but should also include our open-source programs. If you would like to add the projects from our [GitHub Readme](https://github.com/fairfield-programming) onto [this page](https://about.fairfieldprogramming.org/programs/open-source/), that would be great! Make sure that the page you edit is the one inside of the `src` folder, not the `docs` folder. It doesn't need to be styled amazingly but each project should have a quick sentence or two saying what it's for. 

If you would like to work on this, just drop a comment below.

Cheers!

**Comment by aryatalathi** [comment]
yeah! I would like to work on this issue.

**Comment by aryatalathi** [comment]
Yeah! I would like to work on this issue!
