### ISSUE TITLE
Make Header Responsive for Mobile

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#2]
## Idea
The website is going to need to work on mobile. This means that we will need to make the header responsive by using a hamburger design. To check out what I mean by this, you can see [The Brew Society Website](https://brew-society.github.io/).

## Todo
- [ ] Make the Header Responsive

**Comment by fuadop** [comment]
Looks like this has been done too @William-McGonagle 👁️ 🤔

**Comment by William-McGonagle** [comment]
Hey, @fuadop- Sorry for the late reply. These issues are from the old design which we got rid of, but if you want to contribute to the project, I can add some more issues.
