### ISSUE TITLE
Add more detail to the 'Charter Outreach' program description

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#20]
The charter outreach program needs more information on its page, such as information on how to join the program.

To make any changes on the website, simply change the information inside of the [Data Folder](https://github.com/fairfield-programming/fairfield-programming.github.io/tree/master/data), such as [`data/programs.json`](https://github.com/fairfield-programming/fairfield-programming.github.io/blob/master/data/programs.json) for program information. After you've made the change, submit it as a pull request. 

Thanks!
William McGonagle

**Comment by nyedr** [comment]
Hi there, I'd like to ask if you could provide more information on the process for joining the charter outreach program. This would allow me to add more detail to the program description. If there is any additional information you'd like to include, please let me know. Thank you for your help!

**Comment by William-McGonagle** [comment]
@EidanGar 
To join the management of the program (since joining would be running/helping to manage the program), just reach out to Neil Chaudhari by email (chaudharin@fairfieldprogramming.org), with the subject of joining the charter program. The email should just introduce yourself, have some information about who you are and what you've done, and the reason for why you want to help manage the program.

**Comment by nyedr** [comment]
@William-McGonagle No, I mean I need the information so that I can add it to the charter outreach program, I don't really have much to work with right now.
> The charter outreach program needs more information on its page, such as information on how to join the program. 

Also, do you have a min/max word limit for the description?

**Comment by William-McGonagle** [comment]
Hey @EidanGar!

[FPA Charter Program (1).pdf](https://github.com/fairfield-programming/fairfield-programming.github.io/files/10295657/FPA.Charter.Program.1.pdf)

This is a pamphlet we made that describes how the charter program works and why to join. There's not really a word limit to anything you want to add to the page. 

But, please add a paragraph that's similar to the one named "joining" under "cherry-cake" (you can just add a "joining" item to "charter-outreach"). The paragraph should just say to contact Neil Chaudhari (chaudharin@fairfieldprogramming.org) with some information about yourself and why you would like to join.
