### ISSUE TITLE
Add a paragraph explaining how the FPA General Code license is open-source

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#21]
One of the first comments we get on the new FPA General Code license is that it is 'not open source' because it does not follow an archaic definition put together by the OSI. To combat this, we need to add in a short paragraph to [this page](https://about.fairfieldprogramming.org/programs/opensource-legal/fpa-general-code), explaining why the license is in-fact open source.

To make any changes on the website, simply change the information inside of the [Data Folder](https://github.com/fairfield-programming/fairfield-programming.github.io/tree/master/data), such as [`data/programs.json`](https://github.com/fairfield-programming/fairfield-programming.github.io/blob/master/data/programs.json) for program information. After you've made the change, submit it as a pull request. 

The information to change this page is inside the "opensource-legal" section of the `data/programs.json` folder. 

Thanks!
William McGonagle

**Comment by nyedr** [comment]
Hello, I want to claim this issue. I'm assuming I change the description here? Do I replace the text already there or append the paragraph? Can I get a word limit for short?
![Screenshot 2022-12-22 8 28 37 PM](https://user-images.githubusercontent.com/113457465/209252864-6a0bf031-6782-4bc1-ae9e-ea5c074385ca.png)

**Comment by William-McGonagle** [comment]
<img width="1116" alt="Screen Shot 2022-12-22 at 9 35 34 PM" src="https://user-images.githubusercontent.com/19496353/209259567-778f39ce-7866-4d3a-9c07-7e2497f19487.png">

Hi @EidanGar- 
You just edit inside of the fpa-general-code, in the subsection called 'markdown'. Pretty much the markdown content is just an array of lines for a markdown file. So, just add two more strings to the content array. The first string is "## How is the FPA General Code License Open Source?" and the second is the paragraph.

**Comment by nyedr** [comment]
@William-McGonagle can I get a word limit for the paragraph? I'm not sure how short it needs to be.

**Comment by William-McGonagle** [comment]
@EidanGar Sorry- around 40-50 words
