### ISSUE TITLE
Add in 'Charles Ferragu' to the Team List

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#25]
Charles Ferragu is one of our newest board members, and also manages the sponsorships for the FPA. Because of the redesign of the website, we have to start adding people back onto our team list. For now, add basic details about Charles Ferragu– his biography and works paragraph are going to be coming shortly. His email is ferraguc@fairfieldprogramming.org, and he has worked on `charter-outreach` (0) and `charter-events` (1).

To make any changes on the website, simply change the information inside of the [Data Folder](https://github.com/fairfield-programming/fairfield-programming.github.io/tree/master/data), such as [`data/team.json`](https://github.com/fairfield-programming/fairfield-programming.github.io/blob/master/data/team.json) for team member information. After you've made the change, submit it as a pull request.

If you want to claim this issue, just drop a comment here!

Cheers,
William McGonagle

**Comment by elyessAR** [comment]
I can work on this, only few questions about the biography, the work and the photo, can you provide data for that or should I leave them blank for now.

**Comment by William-McGonagle** [comment]
@elyessAR 

We just got Charles to write a biography– I attached it below. For the photo, you can just use [this one](https://avatars.githubusercontent.com/u/96844187?v=4) for now. And for the work paragraph, I guess just write that he works mainly with the charter-outreach and charter-events.

**Biography**
Charles Ferragu is an FPA board member who was born on November 13, 2006 and presently resides in Southport, Connecticut. When he learned that his dear friends William and Neil were launching a non-profit to help address the education shortfall, he decided to join and assist expand the organization with the hopes of impacting many lives.

**Comment by William-McGonagle** [comment]
Hey @elyessAR 

I merged in the work– great as always!

Thank you,
Will
