### ISSUE TITLE
Change all <a> to <Link> in Gatsby files

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#28]
This is pretty self-explanatory, just switch over all of the <a> to <Link> so that there is a better user experience. Make sure that the website works before you put in the pull request.

Also– don't take this if it isn't your first issue.

**Comment by maddy020** [comment]
I want to work over this issue 
Please assign it to me

**Comment by William-McGonagle** [comment]
Sounds great @maddy020– I'll assign it to you

**Comment by William-McGonagle** [comment]
Hey @maddy020 – how is this issue going?

**Comment by maddy020** [comment]
I am unable to set it on my system 
My terminal show this kind of error 
![err](https://user-images.githubusercontent.com/103564105/209803746-84a25e0f-1d78-4002-a3fc-1bbeca23b471.PNG)

**Comment by William-McGonagle** [comment]
Hey @maddy020, try running `npm install --force` and then `gatsby develop` afterwards.

**Comment by William-McGonagle** [comment]
Nice work @pandeyprashant123-coder!
