### ISSUE TITLE
Add in Cookies for Storing User State

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#3]
## Idea
The website won't really have a functioning authentication system until there are cookies built-in to the login and signup pages. What I mean by this is we need a basic library like js-cookie to store whether or not the user is logged in. 

## Todo
- [ ] Import Library to Deal with Cookies
- [ ] Use Cookies to Store Auth Tokens

**Comment by MassiGy** [comment]
Hey @William-McGonagle,

I think I solved this problem within the login issue. (issue #10 )
Please refer to my pull request to see the code.

I will dive into the signup form handler, and see if I can implement a similar behavior for it.

My software of choice is the cookie & cookie-parser packages from npmjs.

Massiles.

**Comment by William-McGonagle** [comment]
I checked out your implementation with the cookies and it looks great!
