### ISSUE TITLE
Fix `===` warnings on project

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#33]
Just replace all of the spots where there are double equals signs (`==`) with triple equal signs (`===`). If you want to know why we need this change just check out, [this article](https://www.freecodecamp.org/news/javascript-triple-equals-sign-vs-double-equals-sign-comparison-operators-explained-with-examples/). 

This issue is reserved for first-time contributors. :smile:

**Comment by SamantaTarun** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by William-McGonagle** [comment]
Sounds good! @tarunsamanta2k20

**Comment by William-McGonagle** [comment]
Hey @tarunsamanta2k20 

Great work! Thanks for the help on that– I merged in the changes.

Cheers,
Will
