### ISSUE TITLE
Add Breadcrumbs Structured Data to Each Page

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#36]
Google structured data allows us to tell Google extra information about each page (allowing us to do better on search). Because of this, we need to add Breadcrumbs for each page of the website.

The best way of doing this is probably adding the Google data in the 'Head' component, and then asking for the information in each of the Head functions (in each page file).

For more information about the Breadcrumbs structured data, [see this page](https://developers.google.com/search/docs/appearance/structured-data/breadcrumb).

Thank you!
Will

**Comment by pandeyprashant123-coder** [comment]
hey @William-McGonagle may I use the `gatsby-plugin-breadcrumb` for this issue

**Comment by William-McGonagle** [comment]
Hey @pandeyprashant123-coder 

Sure– if it works out then totally use it.

Cheers,
Will
