### ISSUE TITLE
Removed Unused Imports

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#37]
There are a ton of unused imports all over the website– it would be awesome if we could get rid of them so that there are fewer warnings during the build.

Oh also, this issue is reserved for first-time contributors to this project. :smile:

Cheers–
Will

**Comment by SamantaTarun** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by William-McGonagle** [comment]
Merged it in- thanks @tarunsamanta2k20!
