### ISSUE TITLE
Add: you can add issue template 

### ISSUE THREAD

**Issue by Niravprajapati1** [fairfield-programming/fairfield-programming.github.io#39]
## What i am suggesting to add ?
I am suggesting to add Issue Templates to the repository, it can be as many categories as needed - primary categories of issues are mostly : bugs, docs, general feature and so on.

### Why to add it ?
Adding an issue Template allows you to organize the issues made by folks in a much better way.

We can know if someone wants to add a feature.
We can know if someone wants to write a test or maybe fix something in the website
Here's a general idea :
image

#### Can i work on it ?
Yes, i will be glad to help an Opensource project grow more !

**Comment by William-McGonagle** [comment]
Hey @Niravprajapati1 

This sounds like a great addition– if you could add a pull request with the issues templates in there, that would be great. You can also do the same thing for [this project](https://github.com/fairfield-programming/standards), and you would get contributor status for both.

Thank you,
Will

**Comment by William-McGonagle** [comment]
Hey @Niravprajapati1 - forgot to say but I merged in your pull request. If your interested, you can submit the same pull to [the vault](https://github.com/fairfield-programming/standards), and get additional contributions.

If not, just let me know and I'll close out this issue.

Thank you,
Will

**Comment by Niravprajapati1** [comment]
Hey @William-McGonagle sure . I will make a pr for that tomorrow!!

**Comment by William-McGonagle** [comment]
Thanks for the PR @Niravprajapati1!
