### ISSUE TITLE
Add "Made with ❤️" to Bottom of Website

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#4]
## Idea
The website is looking great at this point, but I want to add a bit of text inside the footer that says, "Made with ❤️" and links to our GitHub organization. If you want to do this, just drop a comment and I will assign you to the issue. Cheers! 

## Todo
- [ ] Add "Made with ❤️" and link to the GitHub organization

**Comment by William-McGonagle** [comment]
Thanks @Vladislava05!

**Comment by Vladislava05** [comment]
@William-McGonagle 👌
