### ISSUE TITLE
Change search bar on employee page into looking like the search on the Vault

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#47]
This is the second of two websites currently in development from the FPA. Our other website, the Vault, has a really awesome search bar on the [standards page](https://vault.fairfieldprogramming.org/standards). On this website, we have a team page with a search bar, but it should look a little nicer. So, just take the code from the Vault's search bar and add it to the employee page. 

If you would like to take this issue, leave a comment below!

Thanks,
Will

**Comment by pandeyprashant123-coder** [comment]
@William-McGonagle May I work on it?

**Comment by William-McGonagle** [comment]
Hey @pandeyprashant123-coder, sure! 

Also- I've noticed how much you've been helping with the project- if you want to join the organization just hop on our discord server and message me (williammcgonagle#4644)- I'll put the link below.

https://discord.gg/qtu2MXGhcf

Cheers,
Will
