### ISSUE TITLE
Redesign the 404 Page

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#48]
The 404 Page, as found in `src/pages/404.js` looks really bad, so we should add some style to it.

If you would like to help with this issue, leave a comment below. 

Cheers,
Will

**Comment by manasalagisetty** [comment]
I would like to work on this issue, please assign it to me

**Comment by manasalagisetty** [comment]
Hi Team,

Please review this PR for the `redesigning of 404 page`: https://github.com/fairfield-programming/fairfield-programming.github.io/pull/58

Thanks,
Manasa

**Comment by William-McGonagle** [comment]
Hey @manasalagisetty– It looks great! Nice work!
