### ISSUE TITLE
Add a team member page for Tristan Ebrahimi

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#50]
We need to add another team member to the website, to do this, follow the instructions in the readme with the following information.

Name: Tristan Ebrahimi
Biography: "This is placeholder text"
Profile Picture: https://avatars.githubusercontent.com/u/96844187?v=4
Work: Charter Outreach, Charter Events 

To simplify, see Charles Ferragu's information and copy it (remember to add it to the *bottom* of `data/team.json`).

If you'd like to claim this issue, please don't hesitate to let me know.

Cheers,
William McGonagle

**Comment by SamantaTarun** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by William-McGonagle** [comment]
Sure @tarunsamanta2k20- I will assign you right now

**Comment by William-McGonagle** [comment]
Thanks @hanzili for adding these!
