### ISSUE TITLE
Team Search Page is Titled "Programs"

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#51]
### Description

The page [`/team`](https://about.fairfieldprogramming.org/team/) is titled "Programs", so we need to change that so that it is titled "Our Team".

**Comment by SamantaTarun** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by William-McGonagle** [comment]
Thanks for the pull @tarunsamanta2k20!
