### ISSUE TITLE
Add a Link to Our Discord in the Footer

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#53]
Our discord server link is, https://discord.gg/qtu2MXGhcf. We have a link in the footer for our Twitter and our GitHub, but we could use a link for our discord server. This will help drive some more collaborative traffic to the Discord server. 

If you are interested in taking this issue, leave a comment below.

Cheers,
Will

**Comment by SamantaTarun** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by William-McGonagle** [comment]
Nice work @tarunsamanta2k20!
