### ISSUE TITLE
Add a team member page for Hanzi Li

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#54]
We need to add another team member to the website, to do this, follow the instructions in the readme with the following information.

Name: Hanzi Li
Biography: "This is placeholder text"
Profile Picture: https://avatars.githubusercontent.com/u/96844187?v=4
Work: The Vault

To simplify, see Charles Ferragu's information and copy it (remember to add it to the *bottom* of `data/team.json`).

If you'd like to claim this issue, please don't hesitate to let me know.

Cheers,
William McGonagle

**Comment by agung2001** [comment]
hi @William-McGonagle 👋 😄
it seems that this issue been fixed, `Hanzi Li` been added to `data/team.json`

**Comment by William-McGonagle** [comment]
Oh good catch @agung2001, if you want a good issue just let me know!
