### ISSUE TITLE
🚛 Separate Footer into Includes Folder

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#6]
The footer has a "Made with ❤️" sticker on it and a copyright but we need that to be on every page. To do this, we should separate this footer into its own file and use parcel's include system. This will make everything simpler. 

If you want to do this, just leave a comment and I will assign it to you. Cheers!

**Comment by fuadop** [comment]
Hey @William-McGonagle 👋🏾 , Hasn't this been done yet ?, I see a footer on most pages ? or what do you mean ?
