### ISSUE TITLE
Add Team Member Page for Alain Prestige

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#63]
We have a new team member– Alain Prestige! He will be running our Open-Source License List project, so in order to fully bring him onto the team, we need to get him a team member page. To add a team member page, follow the instructions inside of the contribute section (making sure to add him at the bottom of the file to prevent indexing issues). If you are interested in adding this, you can find information about Alain on [his website](https://niprestige.github.io/).

If you want to be assigned to this issue, leave a comment below.

**Comment by pwill12** [comment]
would love to be assigned this issue.

**Comment by William-McGonagle** [comment]
Sounds great @pwill12

**Comment by William-McGonagle** [comment]
Hey @pwill12 – Any news?
