### ISSUE TITLE
Update Our Partners Page to make it more responsive

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#66]
Update the partners page so that on mobile devices, the paragraphs take up the whole page. Right now it doesn't so we gotta fix that.

If you want to take this, leave a comment below.

**Comment by henriqueritter** [comment]
Hey, could I work on this issue?

**Comment by William-McGonagle** [comment]
Thanks for the PR @henriqueritter – great work!
